// File: include/adas/common/Config.hpp
// Configuration loader for ADAS pipeline
// Loads componentConfig.yaml and hardware_map.json
#pragma once

#include "adas/common/Types.hpp"

#include <array>
#include <cstdint>
#include <map>
#include <string>

namespace adas {

// ══════════════════════════════════════════════════════════════════════════════
//                              CONFIGURATION STRUCTURES
// ══════════════════════════════════════════════════════════════════════════════

/// Mount extrinsics (position and orientation in ego frame)
struct MountExtrinsics {
    std::array<float, 3> xyz_m;   // Position [x, y, z] in meters
    std::array<float, 3> rpy_deg; // Rotation [roll, pitch, yaw] in degrees

    MountExtrinsics() : xyz_m{0, 0, 0}, rpy_deg{0, 0, 0} {}
};

/// Time synchronization parameters (FR6)
struct TimeConfig {
    int fusion_hz = 20;     // Fusion tick rate
    int max_skew_ms = 5;    // Maximum inter-sensor skew
    int buffer_ms = 150;    // Buffer depth for alignment
    int late_drop_ms = 100; // Drop threshold for late frames
    int warmup_ticks = 40;  // Warmup period (~2 seconds at 20Hz)
};

/// Camera configuration
struct CameraConfig {
    int width = 960;
    int height = 540;
    int side_width = 640; // Default downscale for side cameras (USB bandwidth safe)
    int side_height = 480;
    int target_fps = 20;
    bool use_mjpeg = true;
};

/// Network ingest configuration (Pi4 rear sector)
struct NetworkConfig {
    int port = 9000;
    int latency_correction_ms = 25; // Timestamp correction offset
    int reconnect_timeout_ms = 5000;
};

/// Front radar configuration (OPS243-A/C)
struct RadarConfig {
    std::string port = "/dev/ttyACM0";
    int baud_rate = 921600;
    int poll_timeout_ms = 50;
    
    // Radar output stream mode:
    // - split_range: speed/range split stream (legacy behavior)
    // - combined_native: native combined speed+range packets (OY)
    std::string output_mode = "split_range";

    // Fusion holding parameters
    int speed_ttl_ms = 900;
    int speed_mag_threshold = 10;
    int range_mag_threshold = 20;
    std::string profile = "combined_hs";
};

/// IMU configuration (BNO085 on Pi, received via ZMQ)
struct IMUConfig {
    std::string bus = "/dev/i2c-1";
    int rate_hz = 100;
    bool use_uart = false;
};

/// Stage E front-fusion and FCW tuning
struct StageEFusionConfig {
    float ttc_aggressive_s = 3.0f;
    int camera_hold_ms = 400;
    float normal_angle_gate_deg = 12.5f;
    float aggressive_angle_gate_deg = 18.0f;
    float aggressive_range_scale = 1.5f;

    // EKF process noise
    float ekf_q_z = 1.0f;
    float ekf_q_vz = 1.2f;
    float ekf_q_theta = 0.04f;
    float ekf_q_theta_dot = 0.06f;

    // EKF measurement noise
    float ekf_r_radar_z = 0.35f;
    float ekf_r_radar_vz = 0.55f;
    float ekf_r_cam_theta = 0.018f;
    float ekf_r_cam_z_weak = 30.0f;
};

/// Complete pipeline configuration
struct Config {
    std::string schema_version = "1.0";
    std::string vehicle = "Civic_2012";

    TimeConfig time;
    CameraConfig cameras;
    NetworkConfig network;
    RadarConfig front_radar;
    IMUConfig imu;
    StageEFusionConfig stage_e_fusion;

    std::map<Mount, MountExtrinsics> mounts;
};

/// Hardware device mapping (generated by DeviceWizard)
struct HardwareMap {
    std::string schema_version = "1.0";
    std::string generated_at;
    std::map<Mount, std::string> mappings; // Mount -> device path
};

// ══════════════════════════════════════════════════════════════════════════════
//                              CONFIG LOADER CLASS
// ══════════════════════════════════════════════════════════════════════════════

/// Configuration loader for YAML and JSON files
class ConfigLoader {
  public:
    /// Load componentConfig.yaml
    /// @param path Path to YAML config file
    /// @return Parsed configuration
    /// @throws std::runtime_error if file cannot be read or parsed
    static Config loadConfig(const std::string &path);

    /// Save componentConfig.yaml (updates mounts section)
    /// @param path Path to YAML config file
    /// @param config Configuration to save
    static void saveConfig(const std::string &path, const Config &config);

    /// Load hardware_map.json
    /// @param path Path to JSON mapping file
    /// @return Parsed hardware mapping
    /// @throws std::runtime_error if file cannot be read or parsed
    static HardwareMap loadHardwareMap(const std::string &path);

    /// Check if hardware_map.json exists
    static bool hardwareMapExists(const std::string &path);

    /// Save hardware_map.json
    /// @param path Output path
    /// @param map Hardware mapping to save
    static void saveHardwareMap(const std::string &path, const HardwareMap &map);

    /// Get default config path (relative to executable)
    static std::string getDefaultConfigPath();

    /// Get default hardware map path
    static std::string getDefaultHardwareMapPath();
};

} // namespace adas
